language: python
python:
  - "3.6"
services:
  - docker
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  - psql -U postgres -c "create extension postgis"
install:
  - pip install codecov Flask Flask_Cors google-cloud-bigtable==0.28.1 bitstring cloud-volume networkx
  - git clone --depth 1 https://github.com/seung-lab/pychunkedgraph.git pychunkedgraph -b svenmd-mst
  - cd pychunkedgraph && python setup.py install && cd ..
  - git clone --depth 1 https://github.com/seung-lab/dynamicannotationdb.git dynamicannotationdb -b master
  - cd dynamicannotationdb && python setup.py install && cd ..
  - git clone --depth 1 https://github.com/seung-lab/emannotationschemas.git emannotationschemas -b master
  - cd emannotationschemas && python emannotationschemas/setup.py install && cd ..
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
env:
  global:
     - MATERIALIZATION_POSTGRES_URI=postgres://postgres:postgres@localhost:5432/postgres
# command to run tests
script:
  - python setup.py pytest # or py.test for Python versions 3.5 and below
cache:   
  pip: true                                                                    
