language: python
python:
  - "3.6"
services:
  - docker
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  - psql -U postgres -c "create extension postgis"
install:
  - pip install codecov Flask Flask_Cors google-cloud-bigtable==0.28.1 bitstring cloud-volume networkx
  - pip install git+git://github.com/seung-lab/pychunkedgraph.git@svenmd-mst#egg=pychunkedgraph
  - pip install git+git://github.com/seung-lab/dynamicannotationdb.git#egg=dynamicannotationdb
  - pip install git+git://github.com/seung-lab/emannotationschemas.git#egg=emannotationschemas
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
env:
  global:
     - MATERIALIZATION_POSTGRES_URI=postgres://postgres:postgres@localhost:5432/postgres
# command to run tests
script:
  - python setup.py pytest # or py.test for Python versions 3.5 and below
cache:   
  pip: true                                                                    
